### ISSUE TITLE
Internet Explorer 11 - app.component

### ISSUE THREAD

**Issue by dzzig** [ExLibrisGroup/primo-explore-package#2]
There seems to be a problem with Internet Explorer 11 and the development model using plug-in directives. Any workaround for this?

Tried JavaScript Recipe 1,2 and 3 without success.
(Edit: Changed version to IE 11)

**Comment by noamamit92** [comment]
@dzzig 

This is understandable, the reason is that in the examples I use the back tic - and this is really only usable if you are using babel (which is supported in the development environment - but not in the flow explained in the documentation)

To solve this there are 2 options:

1. Simple - replace the back tics with regular apostrophe (') and compile the template to a single string , i.e: 
template: '<div layout="row" layout-align="center center">\n                         <md-card flex="80">\n                         <md-card-title>\n                             <md-card-title-text><span class="md-headline">\n                             This is a demo presenting the ability to display query\n                             information below the search box</span>\n                             <span class="md-subhead">Query: {{$ctrl.getQuery()}}</span>\n                             <span class="md-subhead">Scope: {{$ctrl.getSelectdScope()}}</span>\n                             </md-card-title-text>\n                             <md-card-title-media>\n                             <div class="md-media-sm card-media"></div>\n                             </md-card-title-media>\n                         </md-card-title>\n                         <md-card-actions layout="row" layout-align="end center">\n                             <md-button>Action 1</md-button>\n                             <md-button>Action 2</md-button>\n                         </md-card-actions>\n                         </md-card>\n                     </div>'



2. rename the custom.js file to another file name (main.js) then babel will kick in and do the above for you - creating a working custom.js file - this is a development concept of working with advanced js syntax in a file and letting babel compile the code to 'regular' JavaScript


The documentation was updated online
